
spring:
  session:
    store-type: redis
  redis:
    client-name: edge-gateway
  security:
    user:
      name: user
      password: password

management:
  endpoint:
    health:
      show-details: always

server:
  port: 9999
